### PR TITLE
Add connection and query timeout configuration

### PR DESCRIPTION
**Pull request by alexguzun**
Hi! 
In this PR I have added 2 new configurations: `connect-timeout` and `query-timeout `, both with default value of 5 seconds. 

Each setting allow the user to change the default value that is defined in `com.github.mauricio.async.db.Configuration` . 

Best regards and thanks for your work!

### CODE REVIEW

**Comment by okumin** [comment]
@alexguzun LGTM, thanks!
Could you squash commit logs?

**Comment by alexguzun** [comment]
Done. Finally managed to squash the commits.

**Comment by okumin** [comment]
@alexguzun 
Thanks a lot.
I will publish the new version today.

**Comment by okumin** [comment]
@alexguzun I published a new version.
https://github.com/okumin/akka-persistence-sql-async/releases/tag/v0.5.1

Thank you!

**Comment by alexguzun** [comment]
Nice! Thanks for merging it!

**Pull request merged**
